package com.androidvizlab.bachelor.Gui;

import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import javax.swing.JCheckBox;

/**
 *
 * @author Interconnect
 */
public class SettingsDialog extends javax.swing.JDialog {

    //Helper class to read and write to a text file
    private ActionListener actionListener = null;
    private ItemListener itemListener = null;
    
    /**
     * Creates new form SettingsDialog
     */
    public SettingsDialog(java.awt.Frame parent, boolean modal, 
            ActionListener actionListener, ItemListener itemListener) {
        super(parent, modal);
        this.actionListener = actionListener;
        this.itemListener = itemListener;
        initComponents();
        setActionListener();
        setAllErrorLabelsInvisibility();
    }
    
    /**
     * Clears all Text fields in the form
     */
    public void clearForm()
    {
        tfBrokerAddress.setText("");
        tfBrokerPort.setText("");
        tfServerName.setText("");
        tfServerPort.setText("");
        cbUseMachineName.setSelected(false);
        cbBrokerAddress.setSelected(false);
    }
    
    /**
     * Set action listener
     */
    public void setActionListener()
    {
        btnClear.addActionListener(actionListener);
        btnSave.addActionListener(actionListener);
        cbUseMachineName.addItemListener(itemListener);
        cbBrokerAddress.addItemListener(itemListener);
    }
    
    //*** SET TEXT TO TEXT FIELD ***//
    
    public void setBrokerAddressText(String input)
    {
        tfBrokerAddress.setText(input);
    }
    
    public void setBrokerPortText(String input)
    {
        tfBrokerPort.setText(input);
    }
    
    public void setServerNameText(String input)
    {
        tfServerName.setText(input);
    }
    
    public void setServerPortText(String input)
    {
        tfServerPort.setText(input);
    }
    
    //*** GET TEXT FROM TEXT FIELDS ***//
    
    public String getServerAddressText()
    {
        return tfServerName.getText().trim();
    }
    
    public String getServerPortText()
    {
        return tfServerPort.getText().trim();
    }
    
    public String getBrokerAddressText()
    {
        return tfBrokerAddress.getText().trim();
    }
    
    public String getBrokerPortText()
    {
        return tfBrokerPort.getText().trim();
    }
    
    //*** CHECKBOX ACCESS REFERENCE ***//
    public JCheckBox getcbUseMachineName()
    {
        return cbUseMachineName;
    }
    
    public JCheckBox getcbUseLocalIP()
    {
        return cbBrokerAddress;
    }
    
    //*** SET ERROR INDICATOR ***//
    
    /**
     * 
     * @param i 
     */
    public void setError(int i)
    {
        switch(i)
        {
            case 1:
                this.errorLabelServerName.setVisible(true);
                break;
            case 2:
                this.errorLabelServerPort.setVisible(true);
                break;
            case 3:
                this.errorLabelBrokerAddress.setVisible(true);
                break;
            case 4:
                this.errorLabelBrokerPort.setVisible(true);
                break;
        }
    }
    
    /**
     * Set all error labels invisible
     */
    public void setAllErrorLabelsInvisibility()
    {
        this.errorLabelBrokerAddress.setVisible(false);
        this.errorLabelBrokerPort.setVisible(false);
        this.errorLabelServerName.setVisible(false);
        this.errorLabelServerPort.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfServerName = new javax.swing.JTextField();
        tfServerPort = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfBrokerAddress = new javax.swing.JTextField();
        tfBrokerPort = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        cbUseMachineName = new javax.swing.JCheckBox();
        errorLabelServerName = new javax.swing.JLabel();
        errorLabelServerPort = new javax.swing.JLabel();
        errorLabelBrokerAddress = new javax.swing.JLabel();
        errorLabelBrokerPort = new javax.swing.JLabel();
        cbBrokerAddress = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Server Setting");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Server name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Port:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cbUseMachineName, org.jdesktop.beansbinding.ELProperty.create("${!selected}"), tfServerName, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("MQTT");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Broker address(IP):");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Port:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cbBrokerAddress, org.jdesktop.beansbinding.ELProperty.create("${!selected}"), tfBrokerAddress, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);

        tfBrokerPort.setText("1883");

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setText("Clear");

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("Save");

        cbUseMachineName.setSelected(true);
        cbUseMachineName.setText("Use Machine name");

        errorLabelServerName.setForeground(new java.awt.Color(255, 0, 0));
        errorLabelServerName.setText("*");

        errorLabelServerPort.setForeground(new java.awt.Color(255, 0, 0));
        errorLabelServerPort.setText("*");

        errorLabelBrokerAddress.setForeground(new java.awt.Color(255, 0, 0));
        errorLabelBrokerAddress.setText("*");

        errorLabelBrokerPort.setForeground(new java.awt.Color(255, 0, 0));
        errorLabelBrokerPort.setText("*");

        cbBrokerAddress.setSelected(true);
        cbBrokerAddress.setText("Use Localhost  IP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(119, 119, 119)
                                                        .addComponent(tfBrokerPort))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(32, 32, 32)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(cbBrokerAddress)
                                                        .addGap(0, 98, Short.MAX_VALUE))
                                                    .addComponent(tfBrokerAddress))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(errorLabelBrokerAddress)
                                            .addComponent(errorLabelBrokerPort))
                                        .addGap(23, 23, 23))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbUseMachineName)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfServerPort, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                    .addComponent(tfServerName))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(errorLabelServerPort, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                                    .addComponent(errorLabelServerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfServerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errorLabelServerName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbUseMachineName)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errorLabelServerPort)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBrokerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorLabelBrokerAddress)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbBrokerAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBrokerPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(errorLabelBrokerPort))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox cbBrokerAddress;
    private javax.swing.JCheckBox cbUseMachineName;
    private javax.swing.JLabel errorLabelBrokerAddress;
    private javax.swing.JLabel errorLabelBrokerPort;
    private javax.swing.JLabel errorLabelServerName;
    private javax.swing.JLabel errorLabelServerPort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField tfBrokerAddress;
    private javax.swing.JTextField tfBrokerPort;
    private javax.swing.JTextField tfServerName;
    private javax.swing.JTextField tfServerPort;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}